image: /home/ruben/turtlebot3_ws/src/AplicacionROS2/automatix/automatix_my_nav2_system/config/my_map.pgm
mode: trinary
resolution: 0.05
origin: [-3.35, -3.25, 0]
negate: 0
occupied_thresh: 0.65
free_thresh: 0.25